services:
  windows:
    image: dockurr/windows
    container_name: winxpbitcoin
    environment:
      REGION: "en-US"
      KEYBOARD: "en-US"
      LANGUAGE: "English"
      USERNAME: "bill"
      PASSWORD: "gates"
      RAM_SIZE: "1G"
      CPU_CORES: "2"
      DISK_SIZE: "10G"
      VERSION: "xp"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./data:/storage
      - ./share:/shared
    restart: unless-stopped
    stop_grace_period: 2m
